name: Benchmark CI

on:
  push:
    branches: [ main, artifacts ]

jobs:
  build-libraries:
    runs-on: ubuntu-latest
    env:
      CLIENTREPO: ${GITHUB_WORKSPACE}/client
    strategy:
      matrix: 
        ev-lib: ["", libev, libuv, libevent]
    steps:
    - name: install event libs
      run: sudo apt-get install -y libevent-dev libev-dev libuv1-dev
    - name: Checkout c client
      uses: actions/checkout@v2
      with:
        repository: aerospike/aerospike-client-c
        submodules: recursive
        path: client
    - name: Checkout benchmarks 
      uses: actions/checkout@v2
      with: 
        path: main
        submodules: recursive
    - name: Info
      run: make info
      working-directory: main
    - name: Build client lib
      run: make EVENT_LIB=${{ matrix.ev-lib }}
      working-directory: client
    - name: Build benchmark
      run: make EVENT_LIB=${{ matrix.ev-lib }}
      working-directory: main
    - name: Get artifact name
      run: |
        NAME=-${{ matrix.ev-lib}}
        if [ $NAME -eq "-" ]; then NAME="" ; fi
        echo "::set-output name=name::$NAME"
      id: get_name
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with: 
        name: ${{steps.get_name.outputs.name}}
        path: main/target/benchmarks
