name: Build and Test All

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLIENTREPO: ${GITHUB_WORKSPACE}/client
    steps:
    - name: Download libcheck
      uses: dsaltares/fetch-gh-release-asset@0.0.5
      with:
        repo: "libcheck/check"
        version: "tags/0.15.2"
        file: check-0.15.2.tar.gz
    - name: Cache libcheck
      id: cache-libcheck
      uses: actions/cache@v2
      env:
        cache-name: libcheck
      with:
        path: check-0.15.2
        key: check-0.15.2
    - name: Build libcheck
      id: build-libcheck
      if: steps.cache-libcheck.outputs.cache-hit != 'true'
      run: |
        tar xvfz check-0.15.2.tar.gz && cd check-0.15.2
        ./configure
        make
        make check
    - name: install libcheck
      run: |
        cd check-0.15.2
        sudo make install
        sudo ldconfig
    - name: Checkout c client
      uses: actions/checkout@v2
      with:
        repository: aerospike/aerospike-client-c
        submodules: recursive
        path: client
    - name: Checkout benchmarks 
      uses: actions/checkout@v2
      with: 
        path: main
        submodules: recursive
    - name: Info
      run: make info
      working-directory: main
    - name: Build client lib
      run: make
      working-directory: client
    - name: Build benchmark
      run: make
      working-directory: main
    - name: Test
      run: make test
      working-directory: main
    - name: clear temp directories
      run: |
        rm -rf client
        rm -rf main/target
        rm -rf check-0.15.2
        mv main/* .
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.15
      with:
        verbose: false

