name: Build:Main
on:
  push:
    branches: [ main ]
jobs:
  build-libraries:
    runs-on: ubuntu-latest
    env:
      CLIENTREPO: ${GITHUB_WORKSPACE}/client
    strategy:
      matrix: 
        ev-lib: ["", libev, libuv, libevent]
    steps:
    - name: Install event libs
      run: sudo apt-get install -y libevent-dev libev-dev libuv1-dev
    - name: Checkout c client
      uses: actions/checkout@v2
      with:
        repository: aerospike/aerospike-client-c
        submodules: recursive
        path: client
    - name: Checkout benchmarks 
      uses: actions/checkout@v2
      with: 
        path: main
        submodules: recursive
    - name: Build client lib
      run: make EVENT_LIB=${{ matrix.ev-lib }}
      working-directory: client
    - name: Build benchmark
      run: make EVENT_LIB=${{ matrix.ev-lib }}
      working-directory: main
    - name: Get artifact name
      run: |
        set -e
        NAME=-${{ matrix.ev-lib}}
        if [ "${NAME}" = "-" ]; then NAME="" ; fi
        mkdir -p artifacts
        cp target/benchmarks artifacts/${name}
      id: get_name
      working-directory: main
    # - name: Upload artifact
    #   uses: actions/upload-artifact@v2
    #   with: 
    #     name: ${{steps.get_name.outputs.name}}
    #     path: main/target/benchmarks
  pre-release:
    runs-on: ubuntu-latest
    steps: 
      - name: Automatic Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE.md
            artifacts/*
