name: Benchmark CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CLIENTREPO: ${GITHUB_WORKSPACE}/client
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
      with: 
        path: main
        submodules: recursive
    - name: Checkout c client
      uses: actions/checkout@v2
      with:
        repository: aerospike/aerospike-client-c
        submodules: recursive
        path: client
    - name: info
      run: make info
      working-directory: main
    - name: show env
      run: env
    - name: Show contents of main
      run: find `pwd` | sort
      working-directory: main
    - name: Show contents of client
      run: find `pwd` | sort
      working-directory: client    
    - name: make
      run: make
      working-directory: main
