name: Benchmark CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CLIENTREPO: ${GITHUB_WORKSPACE}/client
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
      with: 
        path: ${GITHUB_WORKSPACE}/main
    - name: Checkout c client
      uses: actions/checkout@v2
      with:
        repository: aerospike/aerospike-client-c
        path: ${GITHUB_WORKSPACE}/client
    - name: info
      run: make info
      working-directory: main
    - name: make
      run: make
      working-directory: main
