name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CLIENTREPO: ${GITHUB_WORKSPACE}/client
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
      with: 
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        path: main
    - name: Checkout c client
      uses: actions/checkout@v2
      with:
        repository: citrusleaf/aerospike-client-c
        path: client
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: make
      run: make
